### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by MrDent0n** [gathering/tech-online#32]
Det at vi valgte å bruke Discord åpent gjennom hele avviklinga har vært en knallsukse, vi har fått en god del deltagere som har vært aktive samt "moralsk oppløft" for oss i crew <3

**Comment by HON95** [comment]
Her kan vi nok også ordne at backend pinger oss når folk melder seg på osv. og pinger deltaker når de har fått tildelt plass. Via Discord webhooks av et slag, altså.

**Comment by MrDent0n** [comment]
Det er et godt inspill Håvard!

**Comment by HON95** [comment]
Det var jo snakk om noe e-post eller noe, men en enkelt plattform blir mye bedre.

**Comment by MrDent0n** [comment]
ja. eller til å med at deltagerene kan velge hva som passer dem best
